Repository Tanay-ErrorCode/lupo-skill, pull requests merged in 2024-06, with the labels that each got.

#155 feat: Improve Page Title Handling #44
  src/App.tsx
  src/components/Cards/EventCard/EventCard.tsx
  src/components/DashBoard/DashBoard.tsx
  src/components/EventDetails/EventDetails.tsx
  src/components/ProfilePage/ProfilePage.tsx
  src/components/Signup/Signup.tsx
  src/utils/PageTitle.tsx
Labels: gssoc, level2

#161 FIXED::bug : Users Can Edit Name in Profile Edit Section #153
  src/components/Cards/EditProfile/EditProfile.tsx
Labels: gssoc, level1

#160 feat: User can edit created event date, time and description. #85
  package-lock.json
  package.json
  src/components/Cards/EditEventModal/EditEventModal.tsx
  src/components/Cards/EventCard/EventCard.tsx
  src/components/DashBoard/DashBoard.tsx
  src/components/EventDetails/EventDetails.tsx
  src/components/EventList/EventList.tsx
  src/components/ProfilePage/ProfilePage.tsx
Labels: gssoc, level2

#169 Fixed::bug : SignUp/LogIn Popup and Toast Displayed When User is Logged Out. #165
  src/components/DashBoard/DashBoard.tsx
Labels: gssoc, level1

#170 feat: Add animation to all the modals #164added animation to modals
  package-lock.json
  src/App.css
  src/App.tsx
  src/components/Cards/CreateEvent/CreateEvent.tsx
  src/components/Cards/EditEventModal/EditEventModal.tsx
  src/components/Cards/EditProfile/EditProfile.tsx
  src/components/Signup/Signup.tsx
Labels: gssoc, level1

#174 feat: Option to remove registration of registered event. #168
  src/components/Cards/EventCard/EventCard.css
  src/components/Cards/EventCard/EventCard.tsx
Labels: gssoc, level2

#187 bug : White Space Appears When Scrolling Right on Mobile View (Homepage) #184
  src/components/HomePage/HomePage.tsx
Labels: gssoc, level1

#189 Hover effect Added
  package-lock.json
  src/components/testimonial/TestimonialCard.tsx
  src/components/testimonial/testimonial.css
  src/firebaseConf.ts
Labels: gssoc, level1

#196 bug : Footer Overlapping Pagination Buttons #183
  src/components/Footer/Footer.css
Labels: gssoc, level1

#181 feat: Dynamic Addition of Social Media URL Fields in Edit Profile Modal #163
  src/App.css
  src/components/Cards/EditProfile/EditProfile.css
  src/components/Cards/EditProfile/EditProfile.tsx
  src/components/EventDetails/EventDetails.tsx
  src/components/NavBar/NavBar.tsx
  src/utils/InputLink.tsx
  src/utils/type.ts
Labels: gssoc, level3

#120 Added social media field and improved the validity of social media url.
  package-lock.json
  package.json
  src/components/Cards/EditProfile/EditProfile.tsx
  src/components/HomePage/HomePage.tsx
  src/components/ProfilePage/ProfilePage.tsx
Labels: gssoc, level2

#207 feat: Implement UI for In-App Notifications #206
  src/components/NavBar/NavBar.tsx
  src/components/Notification/NotificationsPanel.tsx
Labels: gssoc, level2

#243 "Styled the Vertical Scrollbar" Matching to "Website Design" theme
  src/index.css
Labels: gssoc, level1

#249 Background image fixed for smaller-device
  LEARN.md
  src/components/HomePage/HomePage.tsx
Labels: gssoc

#241 feat: UI for article writing #230
  package-lock.json
  package.json
  src/App.tsx
  src/components/Article/ArticleWritingPage.css
  src/components/Article/ArticleWritingPage.tsx
  src/components/Article/ArticlesHomepage.css
  src/components/Article/ArticlesHomepage.tsx
  src/components/Article/clap.svg
  src/components/NavBar/NavBar.tsx
Labels: gssoc, level3

#158 Redesigned the Event card
  h
  src/components/Cards/EventCard/EventCard.css
Labels: gssoc, level3

#265 [Feature] : Navbar mobile site changed
  src/components/NavBar/NavBar.tsx
Labels: gssoc, level2

#291 bug : Image overflowing the the article #286
  src/components/Article/ArticlePage.css
Labels: gssoc, level1

#290 feat: Dynamic title display on article reading page #285
  src/components/Article/ArticlePage.tsx
Labels: gssoc, level1
