Repository Tanay-ErrorCode/lupo-skill, pull requests merged in 2024-08, with the labels that each got.

#364 feat: Develop live event WebRTC interface. #358
  src/App.tsx
  src/components/Meetings/MeetingPage.css
  src/components/Meetings/MeetingPage.tsx
Labels: gssoc, level3

#377 Navbar On scroll Effects added
  package-lock.json
  package.json
  src/components/NavBar/NavBar.tsx
Labels: gssoc, level1

#370 feat: want to write backend Of comment section of blogs page #369
  src/components/Article/ArticlePage.tsx
  src/components/Article/ArticlesHomepage.tsx
  src/components/Article/Discussion.css
  src/components/Article/DiscussionModal.tsx
Labels: gssoc, level3

#381 feat:If User has Created 0 events then In created Events Text Should Come With Button #378
  package-lock.json
  src/components/DashBoard/DashBoard.tsx
Labels: gssoc, level1

#386 feat: Profile name or image click behavior in comments. #383
  src/components/Article/DiscussionModal.tsx
Labels: gssoc, level1

#389 eat: Add created articles in the profile page. #384
  src/components/ProfilePage/ProfilePage.css
  src/components/ProfilePage/ProfilePage.tsx
Labels: gssoc, level2

#396 bug : Prevent reading data from server frequently #388
  src/components/Article/ArticlePage.tsx
  src/components/Article/DiscussionModal.tsx
  src/components/Signup/Signup.tsx
Labels: gssoc, level2

#399 Added Scroll indicator in Articles page
  src/components/Article/ArticlePage.tsx
  src/components/ProgressBar/ProgressBar.css
  src/components/ProgressBar/ProgressBar.tsx
Labels: gssoc, level1

#400 feat: File add support for events. #397
  src/components/Cards/CreateEvent/CreateEvent.tsx
  src/components/EventDetails/EventDetails.tsx
  src/utils/FileDropZone.tsx
Labels: gssoc, level3

#405 bug : Can create events before current time. #403
  src/components/Cards/CreateEvent/CreateEvent.tsx
Labels: gssoc, level1

#408 bug : Can't access any page without login #404
  src/components/Cards/CreateEvent/CreateEvent.tsx
  src/components/NavBar/NavBar.tsx
Labels: gssoc, level2
