Repository Tanay-ErrorCode/lupo-skill, pull requests merged in 2024-05, with the labels that each got.

#83 FIXED::bug : Allowing All File Types for Upload in Edit Profile Popup #79
  src/components/Cards/EditProfile/EditProfile.tsx
Labels: level1

#82 Fixed the overlapping of Navbar
  src/App.css
Labels: gssoc, level1

#71 Filter option
  .gitignore
  package-lock.json
  package.json
  src/components/Cards/EventCard/EventCard.css
  src/components/EventList/EventList.tsx
  src/firebaseConf.ts
Labels: gssoc, level1

#94 FIXED::feat: Add Image Cropping Feature for Profile Pictures #80
  package-lock.json
  package.json
  src/components/Cards/EditProfile/EditProfile.tsx
  src/utils/ImageCropper.tsx
Labels: gssoc, level2

#91 Feature : Improved Tag input system
  src/components/Cards/CreateEvent/CreateEvent.tsx
  src/components/Cards/EditProfile/EditProfile.tsx
Labels: enhancement, gssoc, level2, backend

#114 #109 Bug fixed : Unreadable text on create event page
  src/components/Cards/CreateEvent/CreateEvent.css
Labels: gssoc, level1

#116 FIXED::bug : 'Continue With Google' Button Visible on Home Screen Even When Signed In #112
  src/components/HomePage/HomePage.tsx
Labels: level1

#122 Fixed::bug : Profile image on navbar persists after changing profile picture #117
  src/components/Cards/EditProfile/EditProfile.tsx
Labels: level1

#125 FIXED::bug : Google profile image displays on LogIn even if it is updated in database #123
  src/components/Signup/Signup.tsx
Labels: level1

#124 bug : fixing event date
  src/components/Cards/EventCard/EventCard.tsx
Labels: level1

#106 Fixed bug : Star on Github button not working #70
  src/components/HomePage/HomePage.tsx
Labels: gssoc, level1

#131 Smooth scroll animations added.
  package-lock.json
  package.json
  src/components/HomePage/HomePage.tsx
Labels: gssoc, level2

#119 feat: Implement Testimonials Section on Homepage #59
  package-lock.json
  package.json
  src/App.css
  src/components/HomePage/HomePage.tsx
  src/components/testimonial/TestimonialCard.tsx
  src/components/testimonial/TestimonialsCarousel.tsx
  src/components/testimonial/testimonial.css
  src/theme.tsx
Labels: gssoc, level3

#126 Footer added #63
  src/App.css
  src/App.tsx
  src/components/Footer/Footer.css
  src/components/Footer/Footer.tsx
Labels: gssoc, level2

#143 feat: Add animation to the testimonials section. #142
  src/components/HomePage/HomePage.tsx
Labels: gssoc, level2

#146 Signup with gooogle to Login with Google
  src/components/Signup/Signup.tsx
Labels: gssoc
